'use client'

import { useRef, useState } from 'react'
import { Upload, Plus, Trash2, CheckCircle2, XCircle, Loader2, Link as LinkIcon, File as FileIcon, X } from 'lucide-react'
import { uploadCreativeBulk, uploadCreativeFile } from '@/lib/api'
import type { UploadCreativeResult } from '@/lib/api'

interface UploadRow {
  assetType: 'image' | 'video'
  /** 'upload' (default) files straight to S3 via uploadCreativeFile and stores the resulting URL in sourceUrl below; 'url' is the old paste-a-link path — kept for assets that are already hosted somewhere (e.g. a rehosted Higgsfield output). */
  sourceMode: 'upload' | 'url'
  sourceUrl: string
  fileName: string
  fileUploading: boolean
  fileError: string
  headline: string
  primaryText: string
  cta: string
}
function emptyUploadRow(): UploadRow {
  return {
    assetType: 'image', sourceMode: 'upload', sourceUrl: '', fileName: '', fileUploading: false, fileError: '',
    headline: '', primaryText: '', cta: '',
  }
}

interface Product {
  name: string
}

interface CreativeUploadFormProps {
  tenantId: string
  products: Product[]
  /** When set, the topic field is fixed (shown read-only) instead of a free-text input — used from within a Gallery topic page. */
  fixedTopic?: string
  /** When set, uploads land directly in THIS sheet instead of the resolved topic's "Unsorted" sheet. */
  fixedSheetId?: string
  /** Called once, after every row in a batch has uploaded successfully. */
  onUploaded: () => void
}

/**
 * Registers already-made creatives (images/videos you already have, not
 * generated by this pipeline) as real library entries — rehosts each URL
 * onto our own S3, creates a CreativePackage per row, and auto-organizes
 * into the Gallery, just like a generated one. Add a row per asset and
 * submit together; one bad URL doesn't block the rest of the batch — each
 * row shows its own success/failure after submit.
 */
export function CreativeUploadForm({ tenantId, products, fixedTopic, fixedSheetId, onUploaded }: CreativeUploadFormProps) {
  const [product, setProduct] = useState(products[0]?.name ?? '')
  const [topic, setTopic] = useState('')
  const [rows, setRows] = useState<UploadRow[]>([emptyUploadRow()])
  const [uploading, setUploading] = useState(false)
  const [results, setResults] = useState<UploadCreativeResult[] | null>(null)
  const [error, setError] = useState('')
  const [dragIndex, setDragIndex] = useState<number | null>(null)
  const fileInputRefs = useRef<(HTMLInputElement | null)[]>([])

  function addRow() {
    setRows(r => [...r, emptyUploadRow()])
  }

  function removeRow(index: number) {
    setRows(r => r.filter((_, i) => i !== index))
  }

  function updateRow(index: number, patch: Partial<UploadRow>) {
    setRows(r => r.map((row, i) => (i === index ? { ...row, ...patch } : row)))
  }

  async function handleFileSelected(index: number, file: File | undefined | null) {
    if (!file) return
    updateRow(index, { fileUploading: true, fileError: '', fileName: file.name, sourceUrl: '' })
    try {
      const { url } = await uploadCreativeFile(tenantId, file)
      updateRow(index, { fileUploading: false, sourceUrl: url })
    } catch (e) {
      updateRow(index, { fileUploading: false, fileError: e instanceof Error ? e.message : 'Upload failed', fileName: '' })
    }
  }

  function handleDrop(index: number, e: React.DragEvent<HTMLDivElement>) {
    e.preventDefault()
    setDragIndex(null)
    handleFileSelected(index, e.dataTransfer.files?.[0])
  }

  async function handleUpload() {
    if (!product) { setError('Pick a product'); return }
    if (rows.some(r => r.fileUploading)) { setError('Wait for file uploads to finish'); return }
    const incomplete = rows.some(r => !r.sourceUrl.trim() || !r.headline.trim() || !r.primaryText.trim() || !r.cta.trim())
    if (incomplete) {
      setError(rows.some(r => r.sourceMode === 'upload' && !r.sourceUrl.trim())
        ? 'Every row needs a creative file, headline, primary text, and CTA'
        : 'Every row needs a source URL, headline, primary text, and CTA')
      return
    }
    setError('')
    setUploading(true)
    setResults(null)
    try {
      const batchResults = await uploadCreativeBulk(
        tenantId,
        rows.map(r => ({
          productName: product,
          topic: fixedTopic || topic || undefined,
          sheetId: fixedSheetId,
          assetType: r.assetType,
          sourceUrl: r.sourceUrl.trim(),
          copy: { headline: r.headline.trim(), primaryText: r.primaryText.trim(), cta: r.cta.trim() },
        })),
      )
      setResults(batchResults)
      if (batchResults.every(r => r.status === 'completed')) {
        setRows([emptyUploadRow()])
        setTopic('')
        setResults(null)
      }
      onUploaded()
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Failed to upload creatives')
    } finally {
      setUploading(false)
    }
  }

  return (
    <div>
      <div className="grid md:grid-cols-2 gap-3 mb-4">
        <label className="block">
          <span className="text-[11px] font-semibold block mb-1" style={{ color: 'var(--ink-3)' }}>Product (applies to all rows)</span>
          <select value={product} onChange={e => setProduct(e.target.value)} className="input" disabled={uploading}>
            <option value="">Select a product</option>
            {products.map(p => <option key={p.name} value={p.name}>{p.name}</option>)}
          </select>
        </label>
        {fixedTopic ? (
          <label className="block">
            <span className="text-[11px] font-semibold block mb-1" style={{ color: 'var(--ink-3)' }}>Gallery topic</span>
            <input value={fixedTopic} disabled className="input" style={{ color: 'var(--ink-3)' }} />
          </label>
        ) : (
          <label className="block">
            <span className="text-[11px] font-semibold block mb-1" style={{ color: 'var(--ink-3)' }}>Gallery topic (optional — applies to all rows)</span>
            <input value={topic} onChange={e => setTopic(e.target.value)} className="input" placeholder="Defaults to the product name" disabled={uploading} />
          </label>
        )}
      </div>

      <div className="space-y-4 mb-4">
        {rows.map((row, i) => {
          const result = results?.[i]
          return (
            <div key={i} className="rounded-xl p-4" style={{ background: 'var(--surface-warm)', border: '1px solid var(--hairline-light)' }}>
              <div className="flex items-center justify-between mb-3">
                <span className="text-[11px] font-semibold" style={{ color: 'var(--ink-3)' }}>Row {i + 1}</span>
                <div className="flex items-center gap-2">
                  {result && (
                    result.status === 'completed'
                      ? <span className="chip chip-good"><CheckCircle2 size={11} /> Uploaded</span>
                      : <span className="chip chip-bad" title={result.error}><XCircle size={11} /> Failed</span>
                  )}
                  {rows.length > 1 && (
                    <button onClick={() => removeRow(i)} disabled={uploading} className="p-1 rounded-md" style={{ color: 'var(--bad)' }}>
                      <Trash2 size={13} />
                    </button>
                  )}
                </div>
              </div>
              {result?.status === 'failed' && (
                <p className="text-[11px] mb-2" style={{ color: 'var(--bad)' }}>{result.error}</p>
              )}
              <div className="grid md:grid-cols-[120px_1fr] gap-3 mb-3">
                <label className="block">
                  <span className="text-[11px] font-semibold block mb-1" style={{ color: 'var(--ink-3)' }}>Type</span>
                  <select value={row.assetType} onChange={e => updateRow(i, { assetType: e.target.value as 'image' | 'video' })} className="input" disabled={uploading}>
                    <option value="image">Image</option>
                    <option value="video">Video</option>
                  </select>
                </label>
                <div>
                  <div className="flex items-center justify-between mb-1">
                    <span className="text-[11px] font-semibold" style={{ color: 'var(--ink-3)' }}>Creative</span>
                    <div className="flex items-center gap-1">
                      <button
                        type="button"
                        onClick={() => updateRow(i, { sourceMode: 'upload' })}
                        disabled={uploading}
                        className="flex items-center gap-1 px-2 py-0.5 rounded-md text-[11px] font-semibold"
                        style={row.sourceMode === 'upload' ? { background: 'var(--accent-bg)', color: 'var(--accent-strong)' } : { color: 'var(--ink-3)' }}
                      >
                        <Upload size={11} /> Upload file
                      </button>
                      <button
                        type="button"
                        onClick={() => updateRow(i, { sourceMode: 'url' })}
                        disabled={uploading}
                        className="flex items-center gap-1 px-2 py-0.5 rounded-md text-[11px] font-semibold"
                        style={row.sourceMode === 'url' ? { background: 'var(--accent-bg)', color: 'var(--accent-strong)' } : { color: 'var(--ink-3)' }}
                      >
                        <LinkIcon size={11} /> Paste URL
                      </button>
                    </div>
                  </div>

                  {row.sourceMode === 'url' ? (
                    <input value={row.sourceUrl} onChange={e => updateRow(i, { sourceUrl: e.target.value })} className="input" placeholder="https://..." disabled={uploading} />
                  ) : (
                    <div
                      onClick={() => !uploading && !row.fileUploading && fileInputRefs.current[i]?.click()}
                      onDragOver={e => { e.preventDefault(); setDragIndex(i) }}
                      onDragLeave={() => setDragIndex(prev => (prev === i ? null : prev))}
                      onDrop={e => handleDrop(i, e)}
                      className="flex items-center gap-2 rounded-lg px-3 cursor-pointer"
                      style={{
                        height: 38,
                        border: `1.5px dashed ${dragIndex === i ? 'var(--accent-strong)' : 'var(--hairline)'}`,
                        background: dragIndex === i ? 'var(--accent-bg)' : 'var(--surface)',
                      }}
                    >
                      <input
                        ref={el => { fileInputRefs.current[i] = el }}
                        type="file"
                        accept={row.assetType === 'video' ? 'video/*' : 'image/*'}
                        className="hidden"
                        disabled={uploading}
                        onChange={e => handleFileSelected(i, e.target.files?.[0])}
                      />
                      {row.fileUploading ? (
                        <span className="flex items-center gap-1.5 text-[12.5px]" style={{ color: 'var(--ink-3)' }}>
                          <Loader2 size={13} className="animate-spin" /> Uploading…
                        </span>
                      ) : row.sourceUrl && row.fileName ? (
                        <span className="flex items-center gap-1.5 text-[12.5px] font-medium truncate" style={{ color: 'var(--good)' }}>
                          <CheckCircle2 size={13} /> <span className="truncate">{row.fileName}</span>
                          <button
                            type="button"
                            onClick={e => { e.stopPropagation(); updateRow(i, { sourceUrl: '', fileName: '', fileError: '' }) }}
                            className="p-0.5 rounded"
                            style={{ color: 'var(--ink-3)' }}
                          >
                            <X size={12} />
                          </button>
                        </span>
                      ) : (
                        <span className="flex items-center gap-1.5 text-[12.5px]" style={{ color: 'var(--ink-3)' }}>
                          <FileIcon size={13} /> Select file or drag and drop
                        </span>
                      )}
                    </div>
                  )}
                  {row.fileError && <p className="text-[11px] mt-1" style={{ color: 'var(--bad)' }}>{row.fileError}</p>}
                </div>
              </div>
              <div className="grid md:grid-cols-2 gap-3 mb-3">
                <label className="block">
                  <span className="text-[11px] font-semibold block mb-1" style={{ color: 'var(--ink-3)' }}>Headline</span>
                  <input value={row.headline} onChange={e => updateRow(i, { headline: e.target.value })} className="input" disabled={uploading} />
                </label>
                <label className="block">
                  <span className="text-[11px] font-semibold block mb-1" style={{ color: 'var(--ink-3)' }}>CTA</span>
                  <input value={row.cta} onChange={e => updateRow(i, { cta: e.target.value })} className="input" placeholder="e.g. Get My Report" disabled={uploading} />
                </label>
              </div>
              <label className="block">
                <span className="text-[11px] font-semibold block mb-1" style={{ color: 'var(--ink-3)' }}>Primary text</span>
                <textarea value={row.primaryText} onChange={e => updateRow(i, { primaryText: e.target.value })} className="input" style={{ minHeight: 60 }} disabled={uploading} />
              </label>
            </div>
          )
        })}
      </div>

      {error && <p className="text-[13px] mb-3" style={{ color: 'var(--bad)' }}>{error}</p>}

      <div className="flex items-center gap-2">
        <button onClick={addRow} disabled={uploading} className="btn btn-ghost">
          <Plus size={14} /> Add another
        </button>
        <button onClick={handleUpload} disabled={uploading} className="btn btn-primary">
          {uploading ? <Loader2 size={14} className="animate-spin" /> : <Upload size={14} />}
          {uploading ? 'Uploading…' : `Upload ${rows.length > 1 ? `all ${rows.length}` : 'creative'}`}
        </button>
      </div>
    </div>
  )
}
