'use client'

import { useRef, useState } from 'react'
import { Upload, Plus, Trash2, CheckCircle2, XCircle, Loader2, Link as LinkIcon, File as FileIcon, X, AlertTriangle, Crop } from 'lucide-react'
import { uploadCreativeBulk, uploadCreativeFile } from '@/lib/api'
import type { UploadCreativeResult } from '@/lib/api'

/**
 * Where one asset's bytes come from — a file off this machine (default) or a
 * URL it's already hosted at. Both end at the same place: `sourceUrl` holding
 * something the backend can fetch, so nothing downstream has to care which
 * path produced it.
 */
interface AssetSource {
  /** 'upload' sends the file to S3 via uploadCreativeFile and stores the resulting URL in sourceUrl; 'url' is the paste-a-link path — for assets already hosted somewhere (e.g. a rehosted Higgsfield output). */
  sourceMode: 'upload' | 'url'
  sourceUrl: string
  fileName: string
  fileUploading: boolean
  fileError: string
  /** Read off the image itself as soon as it's picked — shown back so you can see what actually got uploaded, and used to fill the ratio tag. Absent for videos and for images we couldn't decode. */
  dimensions?: { width: number; height: number }
}
function emptySource(): AssetSource {
  return { sourceMode: 'upload', sourceUrl: '', fileName: '', fileUploading: false, fileError: '' }
}

/** An alternate ready-made size of the row's creative — same ad, different cut. */
interface SizeRow extends AssetSource {
  /**
   * Filled in automatically from the image's own dimensions; the select is
   * there to override a detection or to tag a shape that isn't one of the
   * four. Display only either way — launch selection measures the real pixels,
   * so a missing tag costs nothing and only a hand-typed wrong one misleads.
   */
  aspectRatio: string
}

interface UploadRow extends AssetSource {
  assetType: 'image' | 'video'
  headline: string
  primaryText: string
  cta: string
  sizes: SizeRow[]
}
function emptyUploadRow(): UploadRow {
  return { ...emptySource(), assetType: 'image', headline: '', primaryText: '', cta: '', sizes: [] }
}

const SIZE_RATIOS = ['1:1', '4:5', '9:16', '16:9']

// Same four placement ratios and the same tolerances the backend classifies
// with (image-resizer.service.ts) — 16:9 is deliberately loose because Meta's
// own 1200x628 link format is 7.5% off a true 16:9 and everyone still calls it
// that. Kept in step with the backend so what the form shows you at pick time
// is what gets stored a moment later.
const RATIO_BANDS: { ratio: string; value: number; tolerance: number }[] = [
  { ratio: '9:16', value: 9 / 16, tolerance: 0.01 },
  { ratio: '4:5', value: 4 / 5, tolerance: 0.01 },
  { ratio: '1:1', value: 1, tolerance: 0.01 },
  { ratio: '16:9', value: 16 / 9, tolerance: 0.08 },
]

/** Which placement ratio these pixels actually are, or '' for a shape that's none of them (a 2:3 photo, say). */
function classifyRatio(width: number, height: number): string {
  const actual = width / height
  return RATIO_BANDS
    .filter(b => Math.abs(actual - b.value) / b.value <= b.tolerance)
    .sort((a, b) => Math.abs(actual - a.value) / a.value - Math.abs(actual - b.value) / b.value)[0]?.ratio ?? ''
}

/**
 * Natural dimensions of an image, or null if it can't be decoded (a video, a
 * URL that 404s, an unsupported format). Reads them off a detached <img>,
 * which needs no CORS grant — only pixel access does, and we want the metadata.
 */
function measureImage(src: string): Promise<{ width: number; height: number } | null> {
  return new Promise(resolve => {
    const img = new window.Image()
    img.onload = () => resolve(img.naturalWidth && img.naturalHeight ? { width: img.naturalWidth, height: img.naturalHeight } : null)
    img.onerror = () => resolve(null)
    img.src = src
  })
}

interface Product {
  name: string
}

interface CreativeUploadFormProps {
  tenantId: string
  products: Product[]
  /** Pre-selected product. Defaults to the first in the list — pass this to prefer another (the Creatives page picks the first ACTIVE one). */
  defaultProduct?: string
  /** When set, the topic field is fixed (shown read-only) instead of a free-text input — used from within a Gallery topic page. */
  fixedTopic?: string
  /** When set, uploads land directly in THIS sheet instead of the resolved topic's "Unsorted" sheet. */
  fixedSheetId?: string
  /** Called once, after every row in a batch has uploaded successfully. */
  onUploaded: () => void
}

/**
 * Registers already-made creatives (images/videos you already have, not
 * generated by this pipeline) as real library entries — rehosts each onto our
 * own S3, creates a CreativePackage per row, and auto-organizes into the
 * Gallery, just like a generated one. Add a row per asset and submit
 * together; one bad asset doesn't block the rest of the batch — each row
 * shows its own success/failure after submit.
 *
 * A row can also carry extra ready-made sizes of the same image (your own
 * 1:1/9:16 cuts). Those file under ONE creative rather than as separate ones,
 * which is what lets launch serve the right size per placement instead of
 * leaving Meta to centre-crop a single asset — the manual counterpart to the
 * auto-resize on a creative's own page.
 */
export function CreativeUploadForm({ tenantId, products, defaultProduct, fixedTopic, fixedSheetId, onUploaded }: CreativeUploadFormProps) {
  const [product, setProduct] = useState(defaultProduct ?? products[0]?.name ?? '')
  const [topic, setTopic] = useState('')
  const [rows, setRows] = useState<UploadRow[]>([emptyUploadRow()])
  const [uploading, setUploading] = useState(false)
  const [results, setResults] = useState<UploadCreativeResult[] | null>(null)
  const [error, setError] = useState('')

  function addRow() {
    setRows(r => [...r, emptyUploadRow()])
  }

  function removeRow(index: number) {
    setRows(r => r.filter((_, i) => i !== index))
  }

  function updateRow(index: number, patch: Partial<UploadRow>) {
    setRows(r => r.map((row, i) => (i === index ? { ...row, ...patch } : row)))
  }

  // Videos can't carry extra sizes — a package holds a single video, so the
  // backend rejects them. Drop any already added rather than submitting a
  // request we know fails.
  function setAssetType(index: number, assetType: 'image' | 'video') {
    updateRow(index, { assetType, ...(assetType === 'video' ? { sizes: [] } : {}) })
  }

  function addSize(rowIndex: number) {
    setRows(r => r.map((row, i) => (i === rowIndex ? { ...row, sizes: [...row.sizes, { ...emptySource(), aspectRatio: '' }] } : row)))
  }

  function removeSize(rowIndex: number, sizeIndex: number) {
    setRows(r => r.map((row, i) => (i === rowIndex ? { ...row, sizes: row.sizes.filter((_, si) => si !== sizeIndex) } : row)))
  }

  function updateSize(rowIndex: number, sizeIndex: number, patch: Partial<SizeRow>) {
    setRows(r => r.map((row, i) => (
      i === rowIndex
        ? { ...row, sizes: row.sizes.map((size, si) => (si === sizeIndex ? { ...size, ...patch } : size)) }
        : row
    )))
  }

  /**
   * Uploads a picked/dropped file and writes the resulting S3 URL back through
   * whichever patcher owns that slot — the row's own asset or one of its
   * sizes. Runs per file, as it's selected, so the submit below only ever
   * deals in URLs and stays fast no matter how many assets a batch carries.
   *
   * Images are measured locally first (decoding a file already on this machine
   * costs nothing) so the form can show what it actually got and fill the
   * ratio tag itself — the file is the truth about its own shape, so a fresh
   * pick re-detects rather than keeping a stale tag.
   */
  async function handleFileSelected(
    patch: (p: Partial<AssetSource>) => void,
    file: File | undefined | null,
    opts: { isImage: boolean; onRatio?: (ratio: string) => void },
  ) {
    if (!file) return
    patch({ fileUploading: true, fileError: '', fileName: file.name, sourceUrl: '', dimensions: undefined })
    if (opts.isImage) {
      const objectUrl = URL.createObjectURL(file)
      try {
        const dims = await measureImage(objectUrl)
        if (dims) {
          patch({ dimensions: dims })
          opts.onRatio?.(classifyRatio(dims.width, dims.height))
        }
      } finally {
        URL.revokeObjectURL(objectUrl)
      }
    }
    try {
      const { url } = await uploadCreativeFile(tenantId, file)
      patch({ fileUploading: false, sourceUrl: url })
    } catch (e) {
      patch({ fileUploading: false, fileError: e instanceof Error ? e.message : 'Upload failed', fileName: '' })
    }
  }

  /**
   * Same detection for a pasted link, once it's finished being typed. Hosts
   * that block hotlinking simply fail to load and leave it undetected — the
   * backend measures the asset for real after re-hosting it either way, so
   * this is a preview of that, not the thing launch relies on.
   */
  async function handleUrlSettled(
    patch: (p: Partial<AssetSource>) => void,
    url: string,
    opts: { isImage: boolean; onRatio?: (ratio: string) => void },
  ) {
    if (!opts.isImage || !url.trim()) return
    const dims = await measureImage(url.trim())
    if (!dims) return
    patch({ dimensions: dims })
    opts.onRatio?.(classifyRatio(dims.width, dims.height))
  }

  async function handleUpload() {
    if (!product) { setError('Pick a product'); return }
    if (rows.some(r => r.fileUploading || r.sizes.some(s => s.fileUploading))) { setError('Wait for file uploads to finish'); return }
    if (rows.some(r => r.sizes.some(s => !s.sourceUrl.trim()))) {
      setError('Every extra size needs a file or URL — remove the empty one if you did not mean to add it')
      return
    }
    const incomplete = rows.some(r => !r.sourceUrl.trim() || !r.headline.trim() || !r.primaryText.trim() || !r.cta.trim())
    if (incomplete) {
      setError(rows.some(r => r.sourceMode === 'upload' && !r.sourceUrl.trim())
        ? 'Every row needs a creative file, headline, primary text, and CTA'
        : 'Every row needs a source URL, headline, primary text, and CTA')
      return
    }
    setError('')
    setUploading(true)
    setResults(null)
    try {
      const batchResults = await uploadCreativeBulk(
        tenantId,
        rows.map(r => ({
          productName: product,
          topic: fixedTopic || topic || undefined,
          sheetId: fixedSheetId,
          assetType: r.assetType,
          sourceUrl: r.sourceUrl.trim(),
          copy: { headline: r.headline.trim(), primaryText: r.primaryText.trim(), cta: r.cta.trim() },
          ...(r.sizes.length
            ? { sizes: r.sizes.map(s => ({ sourceUrl: s.sourceUrl.trim(), aspectRatio: s.aspectRatio || undefined })) }
            : {}),
        })),
      )
      setResults(batchResults)
      // Sizes that failed leave the row 'completed' — keep the form up so
      // that warning is readable instead of resetting it out from under them.
      const clean = batchResults.every(r => r.status === 'completed' && !r.sizeErrors?.length)
      if (clean) {
        setRows([emptyUploadRow()])
        setTopic('')
        setResults(null)
      }
      onUploaded()
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Failed to upload creatives')
    } finally {
      setUploading(false)
    }
  }

  return (
    <div>
      <div className="grid md:grid-cols-2 gap-3 mb-4">
        <label className="block">
          <span className="text-[11px] font-semibold block mb-1" style={{ color: 'var(--ink-3)' }}>Product (applies to all rows)</span>
          <select value={product} onChange={e => setProduct(e.target.value)} className="input" disabled={uploading}>
            <option value="">Select a product</option>
            {products.map(p => <option key={p.name} value={p.name}>{p.name}</option>)}
          </select>
        </label>
        {fixedTopic ? (
          <label className="block">
            <span className="text-[11px] font-semibold block mb-1" style={{ color: 'var(--ink-3)' }}>Gallery topic</span>
            <input value={fixedTopic} disabled className="input" style={{ color: 'var(--ink-3)' }} />
          </label>
        ) : (
          <label className="block">
            <span className="text-[11px] font-semibold block mb-1" style={{ color: 'var(--ink-3)' }}>Gallery topic (optional — applies to all rows)</span>
            <input value={topic} onChange={e => setTopic(e.target.value)} className="input" placeholder="Defaults to the product name" disabled={uploading} />
          </label>
        )}
      </div>

      <div className="space-y-4 mb-4">
        {rows.map((row, i) => {
          const result = results?.[i]
          return (
            <div key={i} className="rounded-xl p-4" style={{ background: 'var(--surface-warm)', border: '1px solid var(--hairline-light)' }}>
              <div className="flex items-center justify-between mb-3">
                <span className="text-[11px] font-semibold" style={{ color: 'var(--ink-3)' }}>Row {i + 1}</span>
                <div className="flex items-center gap-2">
                  {result && (
                    result.status === 'completed'
                      ? <span className="chip chip-good"><CheckCircle2 size={11} /> Uploaded</span>
                      : <span className="chip chip-bad" title={result.error}><XCircle size={11} /> Failed</span>
                  )}
                  {rows.length > 1 && (
                    <button onClick={() => removeRow(i)} disabled={uploading} className="p-1 rounded-md" style={{ color: 'var(--bad)' }}>
                      <Trash2 size={13} />
                    </button>
                  )}
                </div>
              </div>
              {result?.status === 'failed' && (
                <p className="text-[11px] mb-2" style={{ color: 'var(--bad)' }}>{result.error}</p>
              )}
              {!!result?.sizeErrors?.length && (
                <p className="text-[11px] mb-2 flex items-start gap-1" style={{ color: 'var(--warn, var(--bad))' }}>
                  <AlertTriangle size={12} className="shrink-0 mt-0.5" />
                  <span>
                    The creative uploaded, but {result.sizeErrors.length} extra size
                    {result.sizeErrors.length === 1 ? '' : 's'} did not: {result.sizeErrors.map(s => s.error).join('; ')}
                  </span>
                </p>
              )}
              <div className="grid md:grid-cols-[120px_1fr] gap-3 mb-3">
                <label className="block">
                  <span className="text-[11px] font-semibold block mb-1" style={{ color: 'var(--ink-3)' }}>Type</span>
                  <select value={row.assetType} onChange={e => setAssetType(i, e.target.value as 'image' | 'video')} className="input" disabled={uploading}>
                    <option value="image">Image</option>
                    <option value="video">Video</option>
                  </select>
                </label>
                <AssetSourceField
                  label="Creative"
                  source={row}
                  accept={row.assetType === 'video' ? 'video/*' : 'image/*'}
                  disabled={uploading}
                  onPatch={patch => updateRow(i, patch)}
                  onFile={file => handleFileSelected(patch => updateRow(i, patch), file, { isImage: row.assetType === 'image' })}
                  onUrlSettled={url => handleUrlSettled(patch => updateRow(i, patch), url, { isImage: row.assetType === 'image' })}
                />
              </div>

              {row.assetType === 'image' && (
                <div className="mb-3 rounded-lg p-3" style={{ background: 'var(--surface)', border: '1px dashed var(--hairline)' }}>
                  <div className="flex items-center justify-between gap-2 mb-1">
                    <span className="text-[11px] font-semibold flex items-center gap-1.5" style={{ color: 'var(--ink-3)' }}>
                      <Crop size={12} /> Other sizes of this same creative {row.sizes.length > 0 && `(${row.sizes.length})`}
                    </span>
                    <button type="button" onClick={() => addSize(i)} disabled={uploading} className="text-[11px] font-semibold flex items-center gap-1" style={{ color: 'var(--accent-strong)' }}>
                      <Plus size={11} /> Add size
                    </button>
                  </div>
                  <p className="text-[11px] mb-2" style={{ color: 'var(--ink-4)' }}>
                    Optional. Already have this ad cut to 1:1, 9:16 and so on? Add them here and they file under this one creative, so each placement gets the size made for it instead of Meta cropping one asset to fit. The ratio is read off each image as you add it — the dropdown is only there to correct it. Leave this empty and we can auto-resize from the creative&apos;s own page later.
                  </p>
                  {row.sizes.length > 0 && (
                    <div className="space-y-2">
                      {row.sizes.map((size, si) => (
                        <div key={si} className="flex items-start gap-2">
                          <div className="flex-1 min-w-0">
                            <AssetSourceField
                              // The ratio tag lives in the field's own header
                              // row, which keeps it on the same line as the
                              // upload/URL toggle instead of floating above a
                              // field that starts 20px lower.
                              label={
                                <select
                                  value={size.aspectRatio}
                                  onChange={e => updateSize(i, si, { aspectRatio: e.target.value })}
                                  className="input"
                                  style={{ height: 24, padding: '0 6px', fontSize: 11, width: 148 }}
                                  disabled={uploading}
                                  title="Filled in from the image itself — change it only to correct a detection"
                                >
                                  <option value="">Ratio — auto</option>
                                  {SIZE_RATIOS.map(r => <option key={r} value={r}>{r}</option>)}
                                </select>
                              }
                              source={size}
                              accept="image/*"
                              disabled={uploading}
                              compact
                              onPatch={patch => updateSize(i, si, patch)}
                              onFile={file => handleFileSelected(
                                patch => updateSize(i, si, patch),
                                file,
                                { isImage: true, onRatio: ratio => updateSize(i, si, { aspectRatio: ratio }) },
                              )}
                              onUrlSettled={url => handleUrlSettled(
                                patch => updateSize(i, si, patch),
                                url,
                                { isImage: true, onRatio: ratio => updateSize(i, si, { aspectRatio: ratio }) },
                              )}
                            />
                          </div>
                          <button
                            type="button"
                            onClick={() => removeSize(i, si)}
                            disabled={uploading}
                            className="p-1 rounded-md shrink-0"
                            style={{ color: 'var(--bad)' }}
                            aria-label="Remove size"
                          >
                            <Trash2 size={13} />
                          </button>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              )}

              <div className="grid md:grid-cols-2 gap-3 mb-3">
                <label className="block">
                  <span className="text-[11px] font-semibold block mb-1" style={{ color: 'var(--ink-3)' }}>Headline</span>
                  <input value={row.headline} onChange={e => updateRow(i, { headline: e.target.value })} className="input" disabled={uploading} />
                </label>
                <label className="block">
                  <span className="text-[11px] font-semibold block mb-1" style={{ color: 'var(--ink-3)' }}>CTA</span>
                  <input value={row.cta} onChange={e => updateRow(i, { cta: e.target.value })} className="input" placeholder="e.g. Get My Report" disabled={uploading} />
                </label>
              </div>
              <label className="block">
                <span className="text-[11px] font-semibold block mb-1" style={{ color: 'var(--ink-3)' }}>Primary text</span>
                <textarea value={row.primaryText} onChange={e => updateRow(i, { primaryText: e.target.value })} className="input" style={{ minHeight: 60 }} disabled={uploading} />
              </label>
            </div>
          )
        })}
      </div>

      {error && <p className="text-[13px] mb-3" style={{ color: 'var(--bad)' }}>{error}</p>}

      <div className="flex items-center gap-2">
        <button onClick={addRow} disabled={uploading} className="btn btn-ghost">
          <Plus size={14} /> Add another
        </button>
        <button onClick={handleUpload} disabled={uploading} className="btn btn-primary">
          {uploading ? <Loader2 size={14} className="animate-spin" /> : <Upload size={14} />}
          {uploading ? 'Uploading…' : `Upload ${rows.length > 1 ? `all ${rows.length}` : 'creative'}`}
        </button>
      </div>
    </div>
  )
}

interface AssetSourceFieldProps {
  /** Either a plain field name, or a control (the size slots put their ratio select here so it shares the header line). */
  label?: React.ReactNode
  source: AssetSource
  accept: string
  disabled: boolean
  /** Tightens the empty-state wording — for the size slots nested inside a row. */
  compact?: boolean
  onPatch: (patch: Partial<AssetSource>) => void
  onFile: (file: File | undefined | null) => void
  /** Fired when a pasted URL is done being edited, so the parent can measure it. */
  onUrlSettled: (url: string) => void
}

/**
 * One asset slot: pick/drop a file (default) or paste a URL. Owns its own file
 * input and drag state so it can be dropped anywhere a slot is needed — a
 * row's creative or any of its sizes — without the parent tracking a ref per
 * slot, which stops being workable once slots nest.
 */
function AssetSourceField({ label, source, accept, disabled, compact, onPatch, onFile, onUrlSettled }: AssetSourceFieldProps) {
  const inputRef = useRef<HTMLInputElement | null>(null)
  const [dragging, setDragging] = useState(false)
  const busy = disabled || source.fileUploading
  const detectedRatio = source.dimensions ? classifyRatio(source.dimensions.width, source.dimensions.height) : ''

  return (
    <div>
      <div className="flex items-center justify-between gap-2" style={{ marginBottom: 4, minHeight: 24 }}>
        {typeof label === 'string'
          ? <span className="text-[11px] font-semibold" style={{ color: 'var(--ink-3)' }}>{label}</span>
          : label ?? <span />}
        <div className="flex items-center gap-1">
          <button
            type="button"
            onClick={() => onPatch({ sourceMode: 'upload' })}
            disabled={disabled}
            className="flex items-center gap-1 px-2 py-0.5 rounded-md text-[11px] font-semibold"
            style={source.sourceMode === 'upload' ? { background: 'var(--accent-bg)', color: 'var(--accent-strong)' } : { color: 'var(--ink-3)' }}
          >
            <Upload size={11} /> Upload file
          </button>
          <button
            type="button"
            onClick={() => onPatch({ sourceMode: 'url' })}
            disabled={disabled}
            className="flex items-center gap-1 px-2 py-0.5 rounded-md text-[11px] font-semibold"
            style={source.sourceMode === 'url' ? { background: 'var(--accent-bg)', color: 'var(--accent-strong)' } : { color: 'var(--ink-3)' }}
          >
            <LinkIcon size={11} /> Paste URL
          </button>
        </div>
      </div>

      {source.sourceMode === 'url' ? (
        <input
          value={source.sourceUrl}
          onChange={e => onPatch({ sourceUrl: e.target.value, dimensions: undefined })}
          onBlur={e => onUrlSettled(e.target.value)}
          className="input"
          placeholder="https://..."
          disabled={disabled}
        />
      ) : (
        <div
          onClick={() => !busy && inputRef.current?.click()}
          onDragOver={e => { e.preventDefault(); setDragging(true) }}
          onDragLeave={() => setDragging(false)}
          onDrop={e => { e.preventDefault(); setDragging(false); onFile(e.dataTransfer.files?.[0]) }}
          className="flex items-center gap-2 rounded-lg px-3 cursor-pointer"
          style={{
            height: 38,
            border: `1.5px dashed ${dragging ? 'var(--accent-strong)' : 'var(--hairline)'}`,
            background: dragging ? 'var(--accent-bg)' : 'var(--surface)',
          }}
        >
          <input
            ref={inputRef}
            type="file"
            accept={accept}
            className="hidden"
            disabled={disabled}
            onChange={e => { onFile(e.target.files?.[0]); e.target.value = '' }}
          />
          {source.fileUploading ? (
            <span className="flex items-center gap-1.5 text-[12.5px]" style={{ color: 'var(--ink-3)' }}>
              <Loader2 size={13} className="animate-spin" /> Uploading…
            </span>
          ) : source.sourceUrl && source.fileName ? (
            <span className="flex items-center gap-1.5 text-[12.5px] font-medium truncate" style={{ color: 'var(--good)' }}>
              <CheckCircle2 size={13} /> <span className="truncate">{source.fileName}</span>
              <button
                type="button"
                onClick={e => { e.stopPropagation(); onPatch({ sourceUrl: '', fileName: '', fileError: '', dimensions: undefined }) }}
                className="p-0.5 rounded"
                style={{ color: 'var(--ink-3)' }}
              >
                <X size={12} />
              </button>
            </span>
          ) : (
            <span className="flex items-center gap-1.5 text-[12.5px] truncate" style={{ color: 'var(--ink-3)' }}>
              <FileIcon size={13} /> {compact ? 'Select or drop file' : 'Select file or drag and drop'}
            </span>
          )}
        </div>
      )}
      {source.dimensions && (
        <p className="text-[10.5px] mt-1" style={{ color: 'var(--ink-4)' }}>
          {source.dimensions.width}×{source.dimensions.height}
          {detectedRatio
            ? ` — ${detectedRatio}, tagged for you`
            : ' — not one of the four placement ratios, so it stays untagged'}
        </p>
      )}
      {source.fileError && <p className="text-[11px] mt-1" style={{ color: 'var(--bad)' }}>{source.fileError}</p>}
    </div>
  )
}
